#=============================================================
# Makefile LaTeX
#=============================================================
# Author: Angelos Drossos
# (c) 2013, GPLv3
#=============================================================

# (relative) PATH to Main Makefile
MAIN_MAKEFILE = ../..

#=============================================================
# Configuration
#=============================================================

LATEX = pdflatex

OUTFORMAT = pdf

TARGET = fp_paper_sensoransteuerung

OUTDIR = $(MAIN_MAKEFILE)/aux/$(TARGET)


#=============================================================

# include MAIN Makefile
include $(MAIN_MAKEFILE)/Makefile.include
