#=============================================================
# Makefile LaTeX
#=============================================================
# Author: Angelos Drossos
# (c) 2013, GPLv3
#=============================================================

# (relative) PATH to Main Makefile
MAIN_MAKEFILE = ../../..

#=============================================================
# Configuration
#=============================================================

LATEX = pdflatex

OUTFORMAT = pdf

TARGET = vortrag_sn

OUTDIR = $(MAIN_MAKEFILE)/aux/vorlesung/contiki_vortrag


#=============================================================

# include MAIN Makefile
include $(MAIN_MAKEFILE)/Makefile.include
